name: basetime
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.4
  collection: ^1.19.1
  crypto: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.5.3
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  form_validator: ^2.1.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  geoflutterfire_plus: ^0.0.32
  geolocator: ^13.0.2
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  multiselect: ^0.1.1
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/logos/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconapp/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#232323"
  image: assets/iconapp/icon.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center

